version: '3'

services:
  sports:
    image: shuaiscott/zap2xml:latest
    restart: always
    volumes:
        - /xmltvdata:/data
    environment:
        - USERNAME=myemail@email.com
        - PASSWORD=**password**
        - OPT_ARGS=-I -D
        - XMLTV_FILENAME=sports.xml
